# fly.toml app configuration file generated for ij24-api on 2024-09-18T09:22:42-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ij24-api'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.23.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1